### ISSUE TITLE
Concat dynamic page route's name into the file name

### ISSUE THREAD

**Issue by moshfeu** [wix-incubator/corvid#117]
**Is your feature request related to a problem? Please describe.**
A site with 2 dynamic routes that have a file with the same name

![Screen Shot 2019-08-18 at 11 58 24](https://user-images.githubusercontent.com/3723951/63222362-810c1100-c1af-11e9-9855-e5f436bb193d.png)

Getting the same name (except the suffix)

![Screen Shot 2019-08-18 at 12 01 39](https://user-images.githubusercontent.com/3723951/63222407-f5df4b00-c1af-11e9-8aeb-bd0a977f0dba.png)

**Describe the solution you'd like**
The file name can be something like: _DynamicTMSList Pages - DynamicTMS_(SchemaName).d9lxf.js_

**Comment by tomenden** [comment]
Hi @moshfeu ,
Each page is now added to a dedicated folder, I think we can consider this issue resolved. What do you think?

**Comment by moshfeu** [comment]
I haven't used the new version so I can't test it but if this is the case, so yes.
Thanks!
