### ISSUE TITLE
CLI fails to clone site on macbook running on external ssd

### ISSUE THREAD

**Issue by softz4u** [wix-incubator/corvid#133]
When i run this command:
npx corvid clone https://yashaharari.wixsite.com

with my url there, i am prompted to log in via a popup window on my Macbook  (OS X El Capitan version 10.11.6) which runs on an external SSD. 
I enter the login credentials, and the popup window closes. 
Meanwhile, the terminal window says Authentication is done, and then it finishes and gives this error:

[corvid] an error has occurred. see [.corvid/session.log] for details.

and then it goes to the next command line.

When I open it with vim, i see this:

@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@{"message":"Could not get site information from https://yashaharari.wixsite.com","level":"error","stack":"Error: Could not get site information from https://yashaharari.wixsite.com\n    at clone (/Users/yasha/Dropbox/yashaharari.wixsite.com-sandbox/node_modules/corvid-cli/src/apps/clone.js:81:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","timestamp":"2019-09-11T15:35:25.240Z"}

Has anyone else experienced this? Is there a known solution?

Thanks!

**Comment by tomenden** [comment]
Hi,
This problem actually occurs because the url you provided is not of a site.
Wix sites are structured username.wixsite.com/sitename
In your example, sitename is missing
