### ISSUE TITLE
Changelogs describing new version releases

### ISSUE THREAD

**Issue by gasbi** [wix-incubator/corvid#138]
**Is your feature request related to a problem? Please describe.**
Whenever you release a new version of the `corvid-cli`, it is very unclear what has changed. I would like to know the changes before-hand in order to make the best decision on when to update to that version depending on the current state of the development of the site.

**Describe the solution you'd like**
Just a description of all changes made on each new released version of the `corvid-cli`.

**Describe alternatives you've considered**
I am holding on updating to the newest version because I do not know what effects will have on the development team workflows.

**Comment by tomenden** [comment]
Thanks for the request, you're absolutely right :)

For now, we're thinking of adding automatic generation of the CHANGELOG files based on the commit messages. You can check out https://github.com/wix-incubator/corvid/pull/139 which shows the initial changelogs generated by the past commit messages. 

I will appreciate your feedback on whether you find this helpful.
Personally, I think it does help but is probably not sufficient. In the case of releases of new features/breaking changes, I think we should also publish release notes.

**Comment by gasbi** [comment]
Hi @tomenden ! 
Thank you very much for your quick response, really appreciate it!

The automatic changelog files based on commit messages looks fine to me, certainly better than nothing! Although a plain english description for major updates like 0.2.0 are necessary, I believe :) 

I've just seen the v0.2.0 release upgrade guide....that's exactly what I was asking for! 
Thanks!
