### ISSUE TITLE
Keep the coding "IDE" from the online version

### ISSUE THREAD

**Issue by alexander-driveandjob** [wix-incubator/corvid#144]
**Is your feature request related to a problem? Please describe.**
Biggest challenges with using my own IDE is I don't get the nice autocomplete and declaration checks for referring to elements on the front end. On top of that, my IDE pulls up way too many warnings regarding my use of $w which doesn't exist.

**Describe the solution you'd like**
Want to have the same code editor in the local editor as I have in the remote editor.

**Describe alternatives you've considered**
Tried hacking my atom IDE to give similar behaviour. Not elegant.

**Additional context**
I know "use your own IDE" is one of the value props. The reason I use the CLI though, is to be able to work simultaneously with others in my team, and to use github.
Apart from that, thank you for the nice work!

**Comment by dor-itzhaki** [comment]
Hey,
Actually, we have just released support for offline autocomplete.
It is based on typescript definition files, so it requires a code editor with support for typescript. I'm guessing Atom would be fine, but we currently recommend [VSCode](https://code.visualstudio.com/) to get the best experience.

To get autocomplete, you will need to first "push" your site to Wix's online servers, and then install the new `corvid-cli` & `corvid-types` modules (just follow our updated instructions in the [readme](https://github.com/wix-incubator/corvid)).

Please let us know how this works for you...
