### ISSUE TITLE
Error: Command failed: npx corvid clone

### ISSUE THREAD

**Issue by ObserverCR** [wix-incubator/corvid#205]
**Describe the bug**
Cannot clone any site into local project directory. Clone fails during "Getting site information". The issue occurs using both the commands npx create-corvid-app <folder-name> [your-wix-site-url] (if a site url is included) and npx corvid clone <your-wix-site-url> (if local directory was created without cloning project). 

While this issue occurs with all sites, the details below refer to an attempt to clone site: https://www.lithiumvalleywa.com.au/

.corvid/session.log contains the following:

`{"level":"error","name":"FetchError","type":"invalid-json","timestamp":"2020-08-06T05:35:11.350Z"}`

Terminal contains:

```
Cloning your site...

Corvid Technical Preview
Find out more about Corvid at www.wix.com/corvid
The Corvid CLI is used for working with local versions of your Wix sites. Using the CLI you can create new local projects, open a local editor, and pull project updates.
✖ Getting site information

[corvid] an error has occured. see [.corvid/session.log] for details.
Error: Command failed: npx corvid clone https://www.lithiumvalleywa.com.au/
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at executeSync (/Users/cam/.npm/_npx/12523/lib/node_modules/create-corvid-app/src/utils/execSync.js:5:3)
    at cloneSite (/Users/cam/.npm/_npx/12523/lib/node_modules/create-corvid-app/src/create.js:53:3)
    at Command.create (/Users/cam/.npm/_npx/12523/lib/node_modules/create-corvid-app/src/create.js:117:7)
    at Command.listener (/Users/cam/.npm/_npx/12523/lib/node_modules/create-corvid-app/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:314:20)
    at Command.parseArgs (/Users/cam/.npm/_npx/12523/lib/node_modules/create-corvid-app/node_modules/commander/index.js:653:12)
    at Command.parse (/Users/cam/.npm/_npx/12523/lib/node_modules/create-corvid-app/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/Users/cam/.npm/_npx/12523/lib/node_modules/create-corvid-app/src/cli.js:12:4) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 12611,
  stdout: null,
  stderr: null
}
Aborting because an error occured (see above)
```

**To Reproduce**
1. Open terminal.
2. cd \<directory\>
3. npx create-corvid-app \<folder-name\> [your-wix-site-url] 

The error occurs no matter the directory, site url or folder name used. 

**Expected behavior**
Wix site should be cloned into local project directory. 

**Screenshots**
Screenshot of the above terminal output for reference:
<img width="822" alt="CLI ERROR" src="https://user-images.githubusercontent.com/61718927/90579130-5f9d9500-e208-11ea-81a1-e2511f05dcdd.png">

**Desktop:**
 - macOS 10.15.6
 - Node.js 14.8.0
 - npm 6.14.7
 - corvid-types 0.1.104
 - corvid-cli 0.2.10-alpha.0

**Comment by dor-itzhaki** [comment]
Hello,

Please try cloning your site via the `npx corvid-debug clone` command and attach both the console output and the contents the `.corvid/session.log` file that is created after a failed clone.
Let's see if we can find something interesting there...

In addition, can you try cloning using node version 10 (you're currently using version 14) ?
We should support newer versions, but I'd like to test if we can strike that out.

**Comment by ObserverCR** [comment]
Result of corvid-debug clone below:

```
Corvid Technical Preview
Find out more about Corvid at www.wix.com/corvid
The Corvid CLI is used for working with local versions of your Wix sites. Using the CLI you can create new local projects, open a local editor, and pull project updates.
[corvid] 2020-08-20T01:06:10.249Z info:     running [clone https://www.lithiumvalleywa.com.au]
✖ Getting site information

[corvid] an error has occured. see [.corvid/session.log] for details.
[corvid] 2020-08-20T01:06:20.419Z error:    undefined
```

Session Log:
`{"level":"error","name":"FetchError","type":"invalid-json","timestamp":"2020-08-20T01:06:20.416Z"}`

Exact same issue experienced when cloning with node v10:
<img width="1163" alt="Version 10 Error" src="https://user-images.githubusercontent.com/61718927/90705449-49f6a100-e2d6-11ea-8183-2802d45d001c.png">

Happy to try out any other suggestions for getting more detailed logging info.

**Comment by kostagersh** [comment]
Hello, I'm working on this issue now, but i cannot reproduce it locally. Can you temporary add me as site contributor?

**Comment by dor-itzhaki** [comment]
@ObserverCR can you please try to browse to this URL ?
`https://www.wix.com/_api/corvid-devex-service/v1/listUserSites`

what's the reponse that you get ? is the site you're trying to clone included ?

**Comment by dor-itzhaki** [comment]
Also,

Are you asked to sign in each time you try to clone the site?

Can you try to clear some of Electron's local data by deleting these?
`~/Library/Application\ Support/Electron/Cache`
`~/Library/Application\ Support/Electron/Cookies`

Then try to clone again. Did it help?

**Comment by ObserverCR** [comment]
Removing 

~/Library/Application\ Support/Electron/Cache
~/Library/Application\ Support/Electron/Cookies

and then attempting to clone again solved the problem thanks!

Not really relevant now, but the website targeted was included at the url:
https://www.wix.com/_api/corvid-devex-service/v1/listUserSites

**Comment by rafaelbdb** [comment]
Same problem here, but on Linux (Debian 10).
I couldn't find those folders to delete...
Any ideas?

**Comment by dor-itzhaki** [comment]
You should be able to get the base path by executing these inside the project directory:
- `npx electron -i` (will get you into an electron REPL)
- `require('electron').app.getPath('appData')` (will print the base path to the screen)
- CTRL-C (probably twice) to get out of the REPL.

Inside the path you got, you should have an "Electron" folder and the "Cache/Cookies" subfolders within.

**Comment by rafaelbdb** [comment]
`~/.config/Electron` was the folder, but has only 2 subfolders `'Crash Reports'` and `Dictionaries`
