### ISSUE TITLE
Problems creating Dynamic Pages on the local editor

### ISSUE THREAD

**Issue by gasbi** [wix-incubator/corvid#85]
**Describe the bug**
When using the local editor `npx corvid open-editor`, it is not possible to correctly create a Dynamic Page on the site locally.
When I create a Dynamic Page in the local editor everything seems to work fine at first place, but when I close and re-open the editor, the recently created Dynamic Page is not anymore a "Dynamic Page", and instead it can be found as a "Regular page" with all connections to the database broken.
If I try to use the "set to dynamic page" option in the editor for the –now "regular"– page, the page is converted to a dynamic page, but the original `#dynamicDataset` connection is broken (and you can not even delete it from the page) and a duplicate of the `#dynamicDataset` is added to the page which requires to reconnect all elements to it.
This happens every single time you close and re-open the local editor, ending up with countless `#dynamicDatasets` in your page and resulting in the impossibility to work with dynamic pages within the local editor.

**To Reproduce**
1. Clone wix site with corvid-cli `npx corvid clone <siteurl>`
2. Open editor with corvid-cli `npx corvid open-editor`
4. Create a new Dynamic Page within the local editor.
5. Add some elements and connect it to the dynamicDataset.
6. Save changes and close editor.
7. Open local editor again.
8. The page can be found now as a "Regular page" with all dynamic connections broken.
9. If you try to use "set to dynamic page" option, the dataset gets duplicated and all connections are still broken.

**Expected behavior**
The expected behavior would be to be able to correctly create a Dynamic Page as in the online editor.

**Screenshots**
Find a summary of the error in the screenshot below.
<img width="1392" alt="corvid-cli_dynamic-page-bug" src="https://user-images.githubusercontent.com/10176387/60579610-213ae180-9d8c-11e9-8bae-b13aac072303.png">

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.5 (18F132) 
- Version: Corvid CLI v0.1.76
- Site URL: https://eparelllc.wixsite.com/mysite

**Additional context**
We are aware Corvid CLI is in Alpha, and would appreciate any help the Corvid team can provide.

Thanks very much!

**Comment by stevesos** [comment]
Having looked at this it seems that the local editor is not creating the router asset for the page to hook into.

**Comment by tombenezra** [comment]
A fix is merged and released (doesn't require an update for the cli)
